import javafx.application.Application;

import java.io.IOException;


public class Main  {


     static String [] arg;

      public static void main(String[] args) throws IOException, ClassNotFoundException {
      
          System.out.println("Please wait, loading data from online... ");
          loader load = new loader("science", "https://en.wikipedia.org/wiki/Science");
          load = new loader("Knowledge", "https://en.wikipedia.org/wiki/Knowledge");
          load = new loader("Prediction", "https://en.wikipedia.org/wiki/Prediction");
          load = new loader("Astronomy", "https://en.wikipedia.org/wiki/Astronomy");
          load = new loader("Scientific Revolution", "https://en.wikipedia.org/wiki/Scientific_Revolution");
          load = new loader("History of science", "https://en.wikipedia.org/wiki/History_of_science");
          load = new loader("Ancient Egypt", "https://en.wikipedia.org/wiki/Ancient_Egypt");
          load = new loader("Scientific method", "https://en.wikipedia.org/wiki/Scientific_method");
          load = new loader("Branches of science", "https://en.wikipedia.org/wiki/Branches_of_science");

          load = new loader("Empirical evidence", "https://en.wikipedia.org/wiki/Empirical_evidence");
          load = new loader("Formal science", "https://en.wikipedia.org/wiki/Formal_science");
          load = new loader("Natural science", "https://en.wikipedia.org/wiki/Natural_science");
          load = new loader("Hypothesis", "https://en.wikipedia.org/wiki/Hypothesis");
          load = new loader("Social science", "https://en.wikipedia.org/wiki/Social_science");
          load = new loader("Theoretical computer science", "https://en.wikipedia.org/wiki/Theoretical_computer_science");
          load = new loader("Mathematics", "https://en.wikipedia.org/wiki/Mathematics");
          load = new loader("Game theory", "https://en.wikipedia.org/wiki/Game_theory");
          load = new loader("Strategy (game theory)", "https://en.wikipedia.org/wiki/Strategy_(game_theory)");
          load = new loader("Forecasting", "https://en.wikipedia.org/wiki/Forecasting");
          load = new loader("Hydrology", "https://en.wikipedia.org/wiki/Hydrology");
          load = new loader("k-means clustering","https://en.wikipedia.org/wiki/K-means_clustering");
          load = new loader("clustering","https://en.wikipedia.org/wiki/Clustering");
          load = new loader("Buffer","https://en.wikipedia.org/wiki/Buffer");
          load = new loader("Artificial intelligence","https://en.wikipedia.org/wiki/Artificial_intelligence");
          load = new loader("Machine perception","https://en.wikipedia.org/wiki/Machine_perception");
          load = new loader("Computer vision","https://en.wikipedia.org/wiki/Computer_vision");
          load = new loader("Engineering","https://en.wikipedia.org/wiki/Engineering");
          load = new loader("Human intelligence","https://en.wikipedia.org/wiki/Human_intelligence");
          load = new loader("Cattell–Horn–Carroll theory","https://en.wikipedia.org/wiki/Cattell%E2%80%93Horn%E2%80%93Carroll_theory");
          load = new loader("Intellect","https://en.wikipedia.org/wiki/Intellect");
          load = new loader("Intelligent agent","https://en.wikipedia.org/wiki/Intelligent_agent");
          load = new loader("Problem solving","https://en.wikipedia.org/wiki/Problem_solving");
          load = new loader("Mathematical problem","https://en.wikipedia.org/wiki/Mathematical_problem");
          load = new loader("Chaos theory","https://en.wikipedia.org/wiki/Chaos_theory");
          load = new loader("Dynamics","https://en.wikipedia.org/wiki/Dynamics");
          load = new loader("Analytical dynamics","https://en.wikipedia.org/wiki/Analytical_dynamics");
          load = new loader("Psychology","https://en.wikipedia.org/wiki/Psychology");
          load = new loader("Neuroscience","https://en.wikipedia.org/wiki/Neuroscience");
          load = new loader("Abstraction","https://en.wikipedia.org/wiki/Abstraction");
          load = new loader("First principle","https://en.wikipedia.org/wiki/First_principle");
          load = new loader("Formal system","https://en.wikipedia.org/wiki/Formal_system#Logical_system");
          load = new loader("Recursively enumerable set","https://en.wikipedia.org/wiki/Recursively_enumerable_set");
          load = new loader("Primitive recursive function","https://en.wikipedia.org/wiki/Primitive_recursive_function");
          load = new loader("Computability theory","https://en.wikipedia.org/wiki/Computability_theory");
          load = new loader("Turing degree","https://en.wikipedia.org/wiki/Turing_degree");
          load = new loader("Turing reduction","https://en.wikipedia.org/wiki/Turing_reduction");
          load = new loader("Recursive set","https://en.wikipedia.org/wiki/Recursive_set");
          load = new loader("Arithmetical hierarchy","https://en.wikipedia.org/wiki/Arithmetical_hierarchy");
          load = new loader("Hyperarithmetical theory","https://en.wikipedia.org/wiki/Hyperarithmetical_theory");
          load = new loader("Ordinal notation","https://en.wikipedia.org/wiki/Ordinal_notation");
          load = new loader("Transfinite induction","https://en.wikipedia.org/wiki/Transfinite_induction#Transfinite_recursion");
          load = new loader("Cardinality of the continuum","https://en.wikipedia.org/wiki/Cardinality_of_the_continuum");
          load = new loader("Natural number","https://en.wikipedia.org/wiki/Natural_number");
          load = new loader("Measurement","https://en.wikipedia.org/wiki/Measurement");
          load = new loader("Observational error","https://en.wikipedia.org/wiki/Observational_error");
          load = new loader("Probability theory","https://en.wikipedia.org/wiki/Probability_theory");
          load = new loader("Problem of points","https://en.wikipedia.org/wiki/Problem_of_points");


          load = new loader("Topological manifold", "https://en.wikipedia.org/wiki/Topological_manifold");
          load = new loader("Topology", "https://en.wikipedia.org/wiki/Topology");
          load = new loader("Continuous function", "https://en.wikipedia.org/wiki/Continuous_function");
          load = new loader("Domain_theory", "https://en.wikipedia.org/wiki/Domain_theory");
          load = new loader("Denotational_semantics", "https://en.wikipedia.org/wiki/Denotational_semantics");
          load = new loader("Axiomatic_semantics", "https://en.wikipedia.org/wiki/Axiomatic_semantics");
          load = new loader("Mathematical_logic", "https://en.wikipedia.org/wiki/Mathematical_logic");
          load = new loader("Logic", "https://en.wikipedia.org/wiki/Logic");
          load = new loader("Fallacy", "https://en.wikipedia.org/wiki/Fallacy");
          load = new loader("Reason", "https://en.wikipedia.org/wiki/Reason");
          load = new loader("Thought", "https://en.wikipedia.org/wiki/Thought");
          load = new loader("Cognition", "https://en.wikipedia.org/wiki/Cognition");
          load = new loader("Attention", "https://en.wikipedia.org/wiki/Attention");
          load = new loader("Education", "https://en.wikipedia.org/wiki/Education");
          load = new loader("Cognitive_neuroscience", "https://en.wikipedia.org/wiki/Cognitive_neuroscience");
          load = new loader("Functional_neuroimaging", "https://en.wikipedia.org/wiki/Functional_neuroimaging");
          load = new loader("Neuroimaging", "https://en.wikipedia.org/wiki/Neuroimaging");
          load = new loader("Cerebral_cortex", "https://en.wikipedia.org/wiki/Cerebral_cortex");
          load = new loader("Cortex_(anatomy)", "https://en.wikipedia.org/wiki/Cortex_(anatomy)");
          load = new loader("Kidney", "https://en.wikipedia.org/wiki/Kidney");
          load = new loader("Renin","https://en.wikipedia.org/wiki/Renin");
          load = new loader("Vasoconstriction","https://en.wikipedia.org/wiki/Vasoconstriction");
          load = new loader("Vasodilation","https://en.wikipedia.org/wiki/Vasodilation");
          load = new loader("Homeostasis","https://en.wikipedia.org/wiki/Homeostasis");
          load = new loader("Sodium","https://en.wikipedia.org/wiki/Sodium");
          load = new loader("Metal","https://en.wikipedia.org/wiki/Metal");
          load = new loader("Metalloid","https://en.wikipedia.org/wiki/Metalloid");
          load = new loader("Tellurium","https://en.wikipedia.org/wiki/Tellurium");
          load = new loader("Zlatna","https://en.wikipedia.org/wiki/Zlatna");
          load = new loader("Hungarian_language","https://en.wikipedia.org/wiki/Hungarian_language");
          load = new loader("Estonian_language","https://en.wikipedia.org/wiki/Estonian_language");

          load = new loader("Estonia","https://en.wikipedia.org/wiki/Estonia");
          load = new loader("Finnic_languages","https://en.wikipedia.org/wiki/Finnic_languages");
          load = new loader("Endangered_language","https://en.wikipedia.org/wiki/Endangered_language");
          load = new loader("Language_revitalization","https://en.wikipedia.org/wiki/Language_revitalization");
          load = new loader("Language_death","https://en.wikipedia.org/wiki/Language_death");
          load = new loader("Colonialism","https://en.wikipedia.org/wiki/Colonialism");
          load = new loader("Phoenicia","https://en.wikipedia.org/wiki/Phoenicia");
          load = new loader("Carthage","https://en.wikipedia.org/wiki/Carthage");
          load = new loader("Punics","https://en.wikipedia.org/wiki/Punics");
          load = new loader("Phoenician_language","https://en.wikipedia.org/wiki/Phoenician_language");
          load = new loader("Sicily","https://en.wikipedia.org/wiki/Sicily");
          load = new loader("Southern_Italy","https://en.wikipedia.org/wiki/Southern_Italy");
          load = new loader("Insular_Italy","https://en.wikipedia.org/wiki/Insular_Italy");
          load = new loader("Nurra","https://en.wikipedia.org/wiki/Nurra");
          load = new loader("Drought","https://en.wikipedia.org/wiki/Drought");
          load = new loader("Cactus","https://en.wikipedia.org/wiki/Cactus");
          load = new loader("Africa","https://en.wikipedia.org/wiki/Africa");
          load = new loader("Madagascar","https://en.wikipedia.org/wiki/Madagascar");
          load = new loader("Gondwana","https://en.wikipedia.org/wiki/Gondwana");
          load = new loader("Brasiliano_orogeny","https://en.wikipedia.org/wiki/Brasiliano_orogeny");
          load = new loader("Adamastor_Ocean","https://en.wikipedia.org/wiki/Adamastor_Ocean");
          load = new loader("Mantiqueira_Mountains","https://en.wikipedia.org/wiki/Mantiqueira_Mountains");
          load = new loader("Campos_do_Jordão","https://en.wikipedia.org/wiki/Campos_do_Jordão");
          load = new loader("Winter","https://en.wikipedia.org/wiki/Winter");
          load = new loader("Polar_regions_of_Earth","https://en.wikipedia.org/wiki/Polar_regions_of_Earth");
          load = new loader("Antarctica","https://en.wikipedia.org/wiki/Antarctica");

          load = new loader("Fungus", "https://en.wikipedia.org/wiki/Fungus");
          load = new loader("Plant", "https://en.wikipedia.org/wiki/Plant");
          load = new loader("Multicellular_organism", "https://en.wikipedia.org/wiki/Multicellular_organism");
          load = new loader("Dictyostelium", "https://en.wikipedia.org/wiki/Dictyostelium");
          load = new loader("Dipeptide", "https://en.wikipedia.org/wiki/Dipeptide");
          load = new loader("Tripeptide", "https://en.wikipedia.org/wiki/Tripeptide");
          load = new loader("Arame", "https://en.wikipedia.org/wiki/Arame");
          load = new loader("Brown_algae", "https://en.wikipedia.org/wiki/Brown_algae");
          load = new loader("Fucoxanthin", "https://en.wikipedia.org/wiki/Fucoxanthin");
          load = new loader("Diatom", "https://en.wikipedia.org/wiki/Diatom");

          load = new loader("Sahara", "https://en.wikipedia.org/wiki/Sahara");
          load = new loader("Sudan", "https://en.wikipedia.org/wiki/Ethiopia");
          load = new loader("Ethiopia", "https://en.wikipedia.org/wiki/Hypothesis");
          load = new loader("Arabs", "https://en.wikipedia.org/wiki/Arabs");
          load = new loader("Achaemenid_Empire", "https://en.wikipedia.org/wiki/Achaemenid_Empire");
          load = new loader("Persian_people", "https://en.wikipedia.org/wiki/Persian_people");
          load = new loader("Caucasus", "https://en.wikipedia.org/wiki/Caucasus");
          load = new loader("Armenia", "https://en.wikipedia.org/wiki/Armenia");
          load = new loader("Armenian_Kingdom_of_Cilicia", "https://en.wikipedia.org/wiki/Armenian_Kingdom_of_Cilicia");
          load = new loader("Rubenids", "https://en.wikipedia.org/wiki/Rubenids");
          load = new loader("Hethumids","https://en.wikipedia.org/wiki/Hethumids");
          load = new loader("Lampron","https://en.wikipedia.org/wiki/Lampron");
          load = new loader("Kaykhusraw_II","https://en.wikipedia.org/wiki/Kaykhusraw_II");
          load = new loader("Babai_revolt","https://en.wikipedia.org/wiki/Babai_revolt");
          load = new loader("Anatolia","https://en.wikipedia.org/wiki/Anatolia");
          load = new loader("Thrace","https://en.wikipedia.org/wiki/Thrace");
          load = new loader("Southeast_Europe","https://en.wikipedia.org/wiki/Southeast_Europe");
          load = new loader("Greece","https://en.wikipedia.org/wiki/Greece");
          load = new loader("Albania","https://en.wikipedia.org/wiki/Albania");
          load = new loader("Byzantine_Empire","https://en.wikipedia.org/wiki/Byzantine_Empire");
          load = new loader("Constantinople","https://en.wikipedia.org/wiki/Constantinople");
          load = new loader("Hagia_Sophia","https://en.wikipedia.org/wiki/Hagia_Sophia");
          load = new loader("Latin_Empire","https://en.wikipedia.org/wiki/Latin_Empire");
          load = new loader("Franks","https://en.wikipedia.org/wiki/Franks");
          load = new loader("Salian_Franks","https://en.wikipedia.org/wiki/Salian_Franks");
          load = new loader("Belgium","https://en.wikipedia.org/wiki/Belgium");
          load = new loader("United_Kingdom_of_the_Netherlands","https://en.wikipedia.org/wiki/United_Kingdom_of_the_Netherlands");
          load = new loader("Belgian_Revolution","https://en.wikipedia.org/wiki/Belgian_Revolution");
          load = new loader("Brussels","https://en.wikipedia.org/wiki/Brussels");
          load = new loader("Conurbation","https://en.wikipedia.org/wiki/Conurbation");
          load = new loader("Transport","https://en.wikipedia.org/wiki/Transport");
          load = new loader("Motor_vehicle","https://en.wikipedia.org/wiki/Motor_vehicle");
          load = new loader("Per_capita","https://en.wikipedia.org/wiki/Per_capita");
          load = new loader("Estate_(law)","https://en.wikipedia.org/wiki/Estate_(law)");
          load = new loader("Inheritance","https://en.wikipedia.org/wiki/Inheritance");
          load = new loader("Debt","https://en.wikipedia.org/wiki/Debt");
          load = new loader("Morality","https://en.wikipedia.org/wiki/Morality");
          load = new loader("Ontology","https://en.wikipedia.org/wiki/Ontology");
          load = new loader("Hierarchy","https://en.wikipedia.org/wiki/Hierarchy");
          load = new loader("Graph_theory","https://en.wikipedia.org/wiki/Graph_theory");
          load = new loader("Cardinality","https://en.wikipedia.org/wiki/Cardinality");
          load = new loader("Bijection","https://en.wikipedia.org/wiki/Bijection");
          load = new loader("Infinite_set","https://en.wikipedia.org/wiki/Infinite_set");
          load = new loader("Countable_set","https://en.wikipedia.org/wiki/Countable_set");
          load = new loader("Georg_Cantor","https://en.wikipedia.org/wiki/Georg_Cantor");
          load = new loader("Set_theory","https://en.wikipedia.org/wiki/Set_theory");

          load = new loader("Rhamphorhynchoidea", "https://en.wikipedia.org/wiki/Rhamphorhynchoidea");
          load = new loader("Jurassic", "https://en.wikipedia.org/wiki/Jurassic");
          load = new loader("Dinosauromorpha", "https://en.wikipedia.org/wiki/Dinosauromorpha");
          load = new loader("Alps", "https://en.wikipedia.org/wiki/Alps");
          load = new loader("Italy", "https://en.wikipedia.org/wiki/Italy");
          load = new loader("Italy–Tunisia Delimitation Agreement", "https://en.wikipedia.org/wiki/Italy–Tunisia_Delimitation_Agreement");
          load = new loader("Territorial waters", "https://en.wikipedia.org/wiki/Territorial_waters");
          load = new loader("Continental shelf", "https://en.wikipedia.org/wiki/Continental_shelf");
          load = new loader("Turbidity current", "https://en.wikipedia.org/wiki/Turbidity_current");
          load = new loader("Density", "https://en.wikipedia.org/wiki/Density");
          load = new loader("Osmium", "https://en.wikipedia.org/wiki/Osmium");
          load = new loader("Platinum group", "https://en.wikipedia.org/wiki/Platinum_group");
          load = new loader("Ferromagnetism", "https://en.wikipedia.org/wiki/Ferromagnetism");
          load = new loader("Paramagnetism", "https://en.wikipedia.org/wiki/Paramagnetism");
          load = new loader("Magnetism", "https://en.wikipedia.org/wiki/Magnetism");
          load = new loader("Magnetite", "https://en.wikipedia.org/wiki/Magnetite");
          load = new loader("Magnetic moment", "https://en.wikipedia.org/wiki/Magnetic_moment");
          load = new loader("Magnetic dipole", "https://en.wikipedia.org/wiki/Magnetic_dipole");
          load = new loader("Elementary particle", "https://en.wikipedia.org/wiki/Elementary_particle");
          load = new loader("Higgs boson", "https://en.wikipedia.org/wiki/Higgs_boson");
          load = new loader("Peter Higgs","https://en.wikipedia.org/wiki/Peter_Higgs");
          load = new loader("Emeritus","https://en.wikipedia.org/wiki/Emeritus");
          load = new loader("Theoretical physics","https://en.wikipedia.org/wiki/Theoretical_physics");
          load = new loader("Phenomenon","https://en.wikipedia.org/wiki/Phenomenon");
          load = new loader("Noumenon","https://en.wikipedia.org/wiki/Noumenon");
          load = new loader("Sense","https://en.wikipedia.org/wiki/Sense");
          load = new loader("Hearing","https://en.wikipedia.org/wiki/Hearing");
          load = new loader("Auditory science","https://en.wikipedia.org/wiki/Auditory_science");
          load = new loader("Neuroscience","https://en.wikipedia.org/wiki/Neuroscience");
          load = new loader("Molecular neuroscience","https://en.wikipedia.org/wiki/Molecular_neuroscience");
          load = new loader("Genetics","https://en.wikipedia.org/wiki/Genetics");
          load = new loader("Biology","https://en.wikipedia.org/wiki/Biology");
          load = new loader("Molecular genetics","https://en.wikipedia.org/wiki/Molecular_genetics");
          load = new loader("Bacteria","https://en.wikipedia.org/wiki/Bacteria");
          load = new loader("Micrometre","https://en.wikipedia.org/wiki/Micrometre");
          load = new loader("Millimetre","https://en.wikipedia.org/wiki/Millimetre");
          load = new loader("Energy","https://en.wikipedia.org/wiki/Energy");
          load = new loader("Kinetic energy","https://en.wikipedia.org/wiki/Kinetic_energy");
          load = new loader("Velocity","https://en.wikipedia.org/wiki/Velocity");
          load = new loader("Kinematics","https://en.wikipedia.org/wiki/Kinematics");
          load = new loader("Rigid transformation","https://en.wikipedia.org/wiki/Rigid_transformation");
          load = new loader("Screw axis","https://en.wikipedia.org/wiki/Screw axis");
          load = new loader("Plücker coordinates","https://en.wikipedia.org/wiki/Plücker_coordinates");
          load = new loader("Geometric algebra","https://en.wikipedia.org/wiki/Geometric_algebra");
          load = new loader("Vector space","https://en.wikipedia.org/wiki/Vector_space");
          load = new loader("Linear algebra","https://en.wikipedia.org/wiki/Linear_algebra");
          load = new loader("Geometry","https://en.wikipedia.org/wiki/Geometry");

          load = new loader("Anurognathus","https://en.wikipedia.org/wiki/Anurognathus");
          load = new loader("Anurognathidae","https://en.wikipedia.org/wiki/Anurognathidae");
          load = new loader("Pterosaur","https://en.wikipedia.org/wiki/Pterosaur");
          load = new loader("Convergent evolution","https://en.wikipedia.org/wiki/Convergent_evolution");
          load = new loader("Polyphyly","https://en.wikipedia.org/wiki/Polyphyly");
          load = new loader("Monophyly","https://en.wikipedia.org/wiki/Monophyly");
          load = new loader("Tibeto-Burman languages","https://en.wikipedia.org/wiki/Tibeto-Burman_languages");
          load = new loader("Sino-Tibetan languages","https://en.wikipedia.org/wiki/Sino-Tibetan_languages");
          load = new loader("Chinese language","https://en.wikipedia.org/wiki/Chinese_language");
          load = new loader("Kanji","https://en.wikipedia.org/wiki/Kanji");



          load = new loader("French Revolution", "https://en.wikipedia.org/wiki/French_Revolution");
          load = new loader("Kingdom of France", "https://en.wikipedia.org/wiki/Kingdom_of_France");
          load = new loader("Feudalism", "https://en.wikipedia.org/wiki/Feudalism");
          load = new loader("Susan Reynolds", "https://en.wikipedia.org/wiki/Susan_Reynolds");
          load = new loader("Estates of the realm", "https://en.wikipedia.org/wiki/Estates_of_the_realm");


          load = new loader("Scandinavia", "https://en.wikipedia.org/wiki/Scandinavia");
          load = new loader("Faroe Islands", "https://en.wikipedia.org/wiki/Faroe_Islands");
          load = new loader("Autonomous administrative division", "https://en.wikipedia.org/wiki/Autonomous_administrative_division");
          load = new loader("Territory", "https://en.wikipedia.org/wiki/Territory");
          load = new loader("Jurisdiction", "https://en.wikipedia.org/wiki/Jurisdiction");
          load = new loader("Monarch", "https://en.wikipedia.org/wiki/Monarch");
          load = new loader("Personal union", "https://en.wikipedia.org/wiki/Personal_union");
          load = new loader("Commonwealth realm", "https://en.wikipedia.org/wiki/Commonwealth_realm");
          load = new loader("Dominion of Ceylon", "https://en.wikipedia.org/wiki/Dominion_of_Ceylon");
          load = new loader("India", "https://en.wikipedia.org/wiki/India");
          load = new loader("Mahatma Gandhi", "https://en.wikipedia.org/wiki/Mahatma_Gandhi");
          load = new loader("Swaraj", "https://en.wikipedia.org/wiki/Swaraj");

          load = new loader("Bharat Ratna", "https://en.wikipedia.org/wiki/Bharat_Ratna");
          load = new loader("Jayaprakash", "https://en.wikipedia.org/wiki/Jayaprakash_Narayan");
          load = new loader("Sarvepalli Radhakrishnan", "https://en.wikipedia.org/wiki/Sarvepalli_Radhakrishnan");
          load = new loader("Advaita Vedanta","https://en.wikipedia.org/wiki/Advaita_Vedanta");
          load = new loader("Moksha","https://en.wikipedia.org/wiki/Moksha");
          load = new loader("Epistemology","https://en.wikipedia.org/wiki/Epistemology");
          load = new loader("Skepticism","https://en.wikipedia.org/wiki/Skepticism");
          load = new loader("Doctrine","https://en.wikipedia.org/wiki/Doctrine");
          load = new loader("Empire of Japan","https://en.wikipedia.org/wiki/Empire_of_Japan");

          load = new loader("Meiji","https://en.wikipedia.org/wiki/Meiji_(era)");
          load = new loader("Emperor Meiji","https://en.wikipedia.org/wiki/Emperor_Meiji");
          load = new loader("Han system","https://en.wikipedia.org/wiki/Han_system");
          load = new loader("Toyotomi Hideyoshi","https://en.wikipedia.org/wiki/Toyotomi_Hideyoshi");
          load = new loader("Tokugawa Ieyasu","https://en.wikipedia.org/wiki/Tokugawa_Ieyasu");
          load = new loader("Oda Nobunaga","https://en.wikipedia.org/wiki/Oda_Nobunaga");
          load = new loader("Akechi Mitsuhide","https://en.wikipedia.org/wiki/Akechi_Mitsuhide");
          load = new loader("Honnō-ji Incident","https://en.wikipedia.org/wiki/Honn%C5%8D-ji_Incident");
          load = new loader("Kyoto","https://en.wikipedia.org/wiki/Kyoto");
          load = new loader("Keihanshin","https://en.wikipedia.org/wiki/Keihanshin");

          load = new loader("Imperialism","https://en.wikipedia.org/wiki/Imperialism");
          load = new loader("Neuroscience","https://en.wikipedia.org/wiki/Neuroscience");
          load = new loader("Racialization","https://en.wikipedia.org/wiki/Racialization");
          load = new loader("First principle","https://en.wikipedia.org/wiki/First_principle");
          load = new loader("Ethnic studies","https://en.wikipedia.org/wiki/Ethnic_studies");
          load = new loader("Cultural studies","https://en.wikipedia.org/wiki/Cultural_studies");
          load = new loader("Critical theory","https://en.wikipedia.org/wiki/Critical_theory");
          load = new loader("Postmodernism","https://en.wikipedia.org/wiki/Postmodernism");
          load = new loader("Michel Foucault","https://en.wikipedia.org/wiki/Michel_Foucault");
          load = new loader("Sapere aude","https://en.wikipedia.org/wiki/Sapere_aude");
          load = new loader("Polymath","https://en.wikipedia.org/wiki/Polymath");
          load = new loader("Mary Somerville","https://en.wikipedia.org/wiki/Mary_Somerville");
          load = new loader("Falsifiability","https://en.wikipedia.org/wiki/Falsifiability");
          load = new loader("Social science","https://en.wikipedia.org/wiki/Social_science");

          load = new loader("House of Orléans","https://en.wikipedia.org/wiki/House_of_Orl%C3%A9ans");
          load = new loader("July Revolution","https://en.wikipedia.org/wiki/July_Revolution");
          load = new loader("House of Bourbon","https://en.wikipedia.org/wiki/House_of_Bourbon");
          load = new loader("Maria Theresa of Spain","https://en.wikipedia.org/wiki/Maria_Theresa_of_Spain");
          load = new loader("Triple Alliance","https://en.wikipedia.org/wiki/Triple_Alliance_(1668)");
          load = new loader("War of Devolution","https://en.wikipedia.org/wiki/War_of_Devolution");
          load = new loader("Congress","https://en.wikipedia.org/wiki/Congress");



          load = new loader("Jean Bodin", "https://en.wikipedia.org/wiki/Jean_Bodin");
          load = new loader("Natural theology", "https://en.wikipedia.org/wiki/Natural_theology");
          load = new loader("Augustine of Hippo", "https://en.wikipedia.org/wiki/Augustine_of_Hippo");
          load = new loader("Numidia (Roman province)", "https://en.wikipedia.org/wiki/Numidia_(Roman_province)");

          load = new loader("North Africa", "https://en.wikipedia.org/wiki/North_Africa");
          load = new loader("Maghreb", "https://en.wikipedia.org/wiki/Maghreb");
          load = new loader("Iberian Peninsula", "https://en.wikipedia.org/wiki/Iberian_Peninsula");
          load = new loader("Balkans", "https://en.wikipedia.org/wiki/Balkans");
          load = new loader("Musala", "https://en.wikipedia.org/wiki/Musala");
          load = new loader("Sredna Gora", "https://en.wikipedia.org/wiki/Sredna_Gora");
          load = new loader("Stryama", "https://en.wikipedia.org/wiki/Stryama");
          load = new loader("Klisura", "https://en.wikipedia.org/wiki/Klisura_(Bulgaria)");
          load = new loader("Koprivshtitsa", "https://en.wikipedia.org/wiki/Koprivshtitsa");
          load = new loader("Balkanton", "https://en.wikipedia.org/wiki/Balkanton");
          load = new loader("Napster", "https://en.wikipedia.org/wiki/Napster");
          load = new loader("Gnutella", "https://en.wikipedia.org/wiki/Gnutella");
          load = new loader("Nullsoft", "https://en.wikipedia.org/wiki/Nullsoft");
          load = new loader("Justin Frankel", "https://en.wikipedia.org/wiki/Justin_Frankel");
          load = new loader("Winamp", "https://en.wikipedia.org/wiki/Winamp");
          load = new loader("SABAM", "https://en.wikipedia.org/wiki/SABAM");
          load = new loader("Internet service provider","https://en.wikipedia.org/wiki/Internet_service_provider");
          load = new loader("Colocation centre","https://en.wikipedia.org/wiki/Colocation_centre");
          load = new loader("Data center","https://en.wikipedia.org/wiki/Data_center");
          load = new loader("Information technology operations","https://en.wikipedia.org/wiki/Information_technology_operations");
          load = new loader("Distribution","https://en.wikipedia.org/wiki/Distribution_(marketing)");
          load = new loader("Decision-making","https://en.wikipedia.org/wiki/Decision-making");
          load = new loader("Preference","https://en.wikipedia.org/wiki/Preference");
          load = new loader("Insolvency","https://en.wikipedia.org/wiki/Insolvency");
          load = new loader("Legislation","https://en.wikipedia.org/wiki/Legislation");
          load = new loader("Act of Parliament","https://en.wikipedia.org/wiki/Act_of_Parliament");
          load = new loader("Act of Congress","https://en.wikipedia.org/wiki/Act_of_Congress");

          load = new loader("Sovereign state","https://en.wikipedia.org/wiki/Sovereign_state");
          load = new loader("International relations","https://en.wikipedia.org/wiki/International_relations");
          load = new loader("Diplomacy","https://en.wikipedia.org/wiki/Diplomacy");
          load = new loader("Dynamics","https://en.wikipedia.org/wiki/Dynamics");
          load = new loader("Regional power","https://en.wikipedia.org/wiki/Regional_power");
          load = new loader("Ottoman Empire","https://en.wikipedia.org/wiki/Ottoman_Empire");
          load = new loader("Sinai Peninsula","https://en.wikipedia.org/wiki/Sinai_Peninsula");
          load = new loader("Arabic","https://en.wikipedia.org/wiki/Arabic");
          load = new loader("Siwi language","https://en.wikipedia.org/wiki/Siwi_language");
          load = new loader("Ancient Libya","https://en.wikipedia.org/wiki/Ancient_Libya");
          load = new loader("Amazons","https://en.wikipedia.org/wiki/Amazons");
          load = new loader("Clymene","https://en.wikipedia.org/wiki/Clymene_(mythology)");
          load = new loader("Iapetus","https://en.wikipedia.org/wiki/Iapetus");
          load = new loader("Menoetius","https://en.wikipedia.org/wiki/Menoetius");
          load = new loader("Patroclus","https://en.wikipedia.org/wiki/Patroclus");
          load = new loader("Etruscan military history","https://en.wikipedia.org/wiki/Etruscan_military_history");
          load = new loader("Roman army","https://en.wikipedia.org/wiki/Roman_army");
          load = new loader("Seleucid Empire","https://en.wikipedia.org/wiki/Seleucid_Empire");
          load = new loader("Mesopotamia","https://en.wikipedia.org/wiki/Mesopotamia");
          
          
          load = new loader("Pre-nominal letters","https://en.wikipedia.org/wiki/Pre-nominal_letters");
          load = new loader("Post-nominal letters","https://en.wikipedia.org/wiki/Post-nominal_letters");
          load = new loader("Professional certification","https://en.wikipedia.org/wiki/Professional_certification");
          load = new loader("Certification","https://en.wikipedia.org/wiki/Certification");
          load = new loader("Mechanic","https://en.wikipedia.org/wiki/Mechanic");
          load = new loader("Aircraft pilot","https://en.wikipedia.org/wiki/Aircraft_pilot");
          load = new loader("Fixed-wing aircraft","https://en.wikipedia.org/wiki/Fixed-wing_aircraft");

          load = new loader("Airplane", "https://en.wikipedia.org/wiki/Airplane");
          load = new loader("Vehicle", "https://en.wikipedia.org/wiki/Vehicle");
          load = new loader("Ambulance", "https://en.wikipedia.org/wiki/Ambulance");
          load = new loader("Paramedic", "https://en.wikipedia.org/wiki/Paramedic");
          load = new loader("Emergency medical services", "https://en.wikipedia.org/wiki/Emergency_medical_services");
          load = new loader("League of Nations", "https://en.wikipedia.org/wiki/League_of_Nations");
          load = new loader("Mandate for Syria and the Lebanon", "https://en.wikipedia.org/wiki/Mandate_for_Syria_and_the_Lebanon");
          load = new loader("Hatay Province", "https://en.wikipedia.org/wiki/Hatay_Province");
          load = new loader("Adana Province", "https://en.wikipedia.org/wiki/Adana_Province");
          load = new loader("Tahtalı Mountain Range", "https://en.wikipedia.org/wiki/Tahtal%C4%B1_Mountain_Range");
          load = new loader("Taurus Mountains", "https://en.wikipedia.org/wiki/Taurus_Mountains");
          load = new loader("Seleucid Empire", "https://en.wikipedia.org/wiki/Seleucid_Empire");
          load = new loader("Achaemenid Empire", "https://en.wikipedia.org/wiki/Achaemenid_Empire");
          load = new loader("Hellenistic period", "https://en.wikipedia.org/wiki/Hellenistic_period");
          load = new loader("Parthian Empire", "https://en.wikipedia.org/wiki/Parthian_Empire");
          load = new loader("Uzbekistan", "https://en.wikipedia.org/wiki/Uzbekistan");
          load = new loader("Kazakhstan", "https://en.wikipedia.org/wiki/Kazakhstan");
          load = new loader("Khanate of Kokand", "https://en.wikipedia.org/wiki/Khanate_of_Kokand");
          load = new loader("Karluk languages", "https://en.wikipedia.org/wiki/Karluk_languages");
          load = new loader("Chagatai language", "https://en.wikipedia.org/wiki/Chagatai_language");
          load = new loader("Indo-Persian culture","https://en.wikipedia.org/wiki/Indo-Persian_culture");
          load = new loader("Akbar","https://en.wikipedia.org/wiki/Akbar");
          load = new loader("Mughal Empire","https://en.wikipedia.org/wiki/Mughal_Empire");
          load = new loader("Sepoy","https://en.wikipedia.org/wiki/Sepoy");
          load = new loader("Indian Rebellion of 1857","https://en.wikipedia.org/wiki/Indian_Rebellion_of_1857");
          load = new loader("Hindus","https://en.wikipedia.org/wiki/Hindus");
          load = new loader("Kathmandu","https://en.wikipedia.org/wiki/Kathmandu");
          load = new loader("South Asian Association for Regional Cooperation","https://en.wikipedia.org/wiki/South_Asian_Association_for_Regional_Cooperation");
          load = new loader("South Asia","https://en.wikipedia.org/wiki/South_Asia");
          load = new loader("Iron Age","https://en.wikipedia.org/wiki/Iron_Age");
          load = new loader("Wheathampstead","https://en.wikipedia.org/wiki/Wheathampstead");
          load = new loader("Harpenden","https://en.wikipedia.org/wiki/Harpenden");
          load = new loader("United Nations Association","https://en.wikipedia.org/wiki/United_Nations_Association");
          load = new loader("Howard Penman","https://en.wikipedia.org/wiki/Howard_Penman");
          load = new loader("Penman equation","https://en.wikipedia.org/wiki/Penman_equation");
          load = new loader("Potential evaporation","https://en.wikipedia.org/wiki/Potential_evaporation");
          load = new loader("Evapotranspiration","https://en.wikipedia.org/wiki/Evapotranspiration#Potential_evapotranspiration");
          load = new loader("Steppe","https://en.wikipedia.org/wiki/Steppe");
          load = new loader("Crimean Mountains","https://en.wikipedia.org/wiki/Crimean_Mountains");
          load = new loader("Crimean Tatar language","https://en.wikipedia.org/wiki/Crimean_Tatar_language");
          load = new loader("Crimea","https://en.wikipedia.org/wiki/Crimea");
          load = new loader("East Germanic languages","https://en.wikipedia.org/wiki/East_Germanic_languages");
          load = new loader("Barbarian kingdoms","https://en.wikipedia.org/wiki/Barbarian_kingdoms");
          load = new loader("Roman Empire","https://en.wikipedia.org/wiki/Roman_Empire");
          load = new loader("Classical antiquity","https://en.wikipedia.org/wiki/Classical_antiquity");
          load = new loader("1st millennium BC","https://en.wikipedia.org/wiki/1st_millennium_BC");
          load = new loader("Axial Age","https://en.wikipedia.org/wiki/Axial_Age");
          load = new loader("Old World","https://en.wikipedia.org/wiki/Old_World");
          load = new loader("Atlantic Ocean","https://en.wikipedia.org/wiki/Atlantic_Ocean");
          load = new loader("Republic of the Congo","https://en.wikipedia.org/wiki/Republic_of_the_Congo");
          load = new loader("Jonathan Friedman","https://en.wikipedia.org/wiki/Jonathan_Friedman");
          load = new loader("State terrorism","https://en.wikipedia.org/wiki/State_terrorism");
          load = new loader("Totalitarianism","https://en.wikipedia.org/wiki/Totalitarianism");
          load = new loader("Resistance movement","https://en.wikipedia.org/wiki/Resistance_movement");
          load = new loader("Combatant","https://en.wikipedia.org/wiki/Combatant");
          load = new loader("Ambush","https://en.wikipedia.org/wiki/Ambush");
          load = new loader("Guerrilla warfare","https://en.wikipedia.org/wiki/Guerrilla_warfare");


          load = new loader("Stalinism", "https://en.wikipedia.org/wiki/Stalinism");
          load = new loader("Joseph Stalin", "https://en.wikipedia.org/wiki/Joseph_Stalin");
          load = new loader("Vladimir Lenin", "https://en.wikipedia.org/wiki/Vladimir_Lenin");
          load = new loader("General Jewish Labour Bund", "https://en.wikipedia.org/wiki/General_Jewish_Labour_Bund");
          load = new loader("Mensheviks", "https://en.wikipedia.org/wiki/Mensheviks");
          load = new loader("October Revolution", "https://en.wikipedia.org/wiki/October_Revolution");
          load = new loader("Democratic centralism", "https://en.wikipedia.org/wiki/Democratic_centralism");
          load = new loader("Bolsheviks", "https://en.wikipedia.org/wiki/Bolsheviks");
          load = new loader("Prince Vasili Alexandrovich of Russia", "https://en.wikipedia.org/wiki/Prince_Vasili_Alexandrovich_of_Russia");
          load = new loader("Prince Andrew Romanov", "https://en.wikipedia.org/wiki/Prince_Andrew_Romanov");
          load = new loader("House of Romanov", "https://en.wikipedia.org/wiki/House_of_Romanov");
          load = new loader("Rurik dynasty", "https://en.wikipedia.org/wiki/Rurik_dynasty");
          load = new loader("Principality of Beloozero", "https://en.wikipedia.org/wiki/Principality_of_Beloozero");
          load = new loader("Lake Beloye (Vologda Oblast)", "https://en.wikipedia.org/wiki/Lake_Beloye_(Vologda_Oblast)");
          load = new loader("Belozersky District, Vologda Oblast", "https://en.wikipedia.org/wiki/Belozersky_District,_Vologda_Oblast");
          load = new loader("Belozersk", "https://en.wikipedia.org/wiki/Belozersk");
          load = new loader("Vologda", "https://en.wikipedia.org/wiki/Vologda");
          load = new loader("Vyacheslav Molotov", "https://en.wikipedia.org/wiki/Vyacheslav_Molotov");
          load = new loader("Soviet Union", "https://en.wikipedia.org/wiki/Soviet_Union");
          load = new loader("Cultural icon", "https://en.wikipedia.org/wiki/Cultural_icon");
          load = new loader("Cuckoo clock","https://en.wikipedia.org/wiki/Cuckoo_clock");
          load = new loader("Wallace Collection","https://en.wikipedia.org/wiki/Wallace_Collection");
          load = new loader("Horology","https://en.wikipedia.org/wiki/Horology");
          load = new loader("Clock","https://en.wikipedia.org/wiki/Clock#Early_mechanical_clocks");
          load = new loader("Hooke's law","https://en.wikipedia.org/wiki/Hooke%27s_law");
          load = new loader("Viscosity","https://en.wikipedia.org/wiki/Viscosity");
          load = new loader("Lithosphere–asthenosphere boundary","https://en.wikipedia.org/wiki/Lithosphere%E2%80%93asthenosphere_boundary");
          load = new loader("Lithosphere","https://en.wikipedia.org/wiki/Lithosphere");
          load = new loader("Tectonic uplift","https://en.wikipedia.org/wiki/Tectonic_uplift");
          load = new loader("Outcrop","https://en.wikipedia.org/wiki/Outcrop");
          load = new loader("Lithology","https://en.wikipedia.org/wiki/Lithology");
          load = new loader("Attrition","https://en.wikipedia.org/wiki/Attrition_(erosion)");
          load = new loader("Abrasion","https://en.wikipedia.org/wiki/Abrasion_(geology)");
          load = new loader("Erosion","https://en.wikipedia.org/wiki/Erosion");
          load = new loader("Pebble","https://en.wikipedia.org/wiki/Pebble");
          load = new loader("Cobble","https://en.wikipedia.org/wiki/Cobble_(geology)");
          load = new loader("Grain size","https://en.wikipedia.org/wiki/Grain_size");
          load = new loader("Sediment","https://en.wikipedia.org/wiki/Sediment");
          load = new loader("Clastic rock","https://en.wikipedia.org/wiki/Clastic_rock");
          load = new loader("Siltstone","https://en.wikipedia.org/wiki/Siltstone");
          load = new loader("Mudrock","https://en.wikipedia.org/wiki/Mudrock");
          load = new loader("Sedimentary rock","https://en.wikipedia.org/wiki/Sedimentary_rock");
          load = new loader("Metamorphic rock","https://en.wikipedia.org/wiki/Metamorphic_rock");
          load = new loader("Eburnean orogeny","https://en.wikipedia.org/wiki/Eburnean_orogeny");
          load = new loader("Columbia","https://en.wikipedia.org/wiki/Columbia_(supercontinent)");
          load = new loader("Rodinia","https://en.wikipedia.org/wiki/Rodinia");
          load = new loader("Neoproterozoic","https://en.wikipedia.org/wiki/Neoproterozoic");
          load = new loader("Mesoproterozoic","https://en.wikipedia.org/wiki/Mesoproterozoic");
          load = new loader("Proterozoic","https://en.wikipedia.org/wiki/Proterozoic");
          load = new loader("Eukaryote","https://en.wikipedia.org/wiki/Eukaryote");
          load = new loader("Protein turnover","https://en.wikipedia.org/wiki/Protein_turnover");
          load = new loader("Protein","https://en.wikipedia.org/wiki/Protein");
          load = new loader("Martinus Beijerinck","https://en.wikipedia.org/wiki/Martinus_Beijerinck");
          load = new loader("Metabolism","https://en.wikipedia.org/wiki/Metabolism");
          load = new loader("Anaerobic organism","https://en.wikipedia.org/wiki/Anaerobic_organism");
          load = new loader("Biophysical environment","https://en.wikipedia.org/wiki/Biophysical_environment");
          load = new loader("Environmental protection","https://en.wikipedia.org/wiki/Environmental_protection");


          load = new loader("Zermelo–Fraenkel_set_theory","https://en.wikipedia.org/wiki/Zermelo–Fraenkel_set_theory");
          load = new loader("David_Hilbert","https://en.wikipedia.org/wiki/David_Hilbert");
          load = new loader("Formal_language","https://en.wikipedia.org/wiki/Formal_language");
          load = new loader("Pragmatics","https://en.wikipedia.org/wiki/Pragmatics");
          load = new loader("Linguistics","https://en.wikipedia.org/wiki/Linguistics");
          load = new loader("Intention","https://en.wikipedia.org/wiki/Intention");
          load = new loader("Memory","https://en.wikipedia.org/wiki/Memory");
          load = new loader("Supercluster","https://en.wikipedia.org/wiki/Supercluster");
          load = new loader("Hubble_expansion","https://en.wikipedia.org/wiki/Hubble_expansion");
          load = new loader("Friedmann_equations","https://en.wikipedia.org/wiki/Friedmann_equations");
          load = new loader("Perfect_fluid","https://en.wikipedia.org/wiki/Perfect_fluid");
          load = new loader("Minkowski_spacetime","https://en.wikipedia.org/wiki/Minkowski_spacetime");
          load = new loader("Galilean_group","https://en.wikipedia.org/wiki/Galilean_group");
          load = new loader("Semidirect_product","https://en.wikipedia.org/wiki/Semidirect_product");
          load = new loader("Cartesian_product","https://en.wikipedia.org/wiki/Cartesian_product");
          load = new loader("Tuple","https://en.wikipedia.org/wiki/Tuple");


          load.Calculate_similar_data();
          load.show_similar_data();
          load.show_disjoint_set();


          arg =args;
          show_gui();
      }

      public static void show_gui(){
          Application.launch(gui.class, arg);

      }

}
